name = "arkive-relay"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "df08a4524c6b150c79348335a7211040"

[[d1_databases]]
binding = "DB"
database_name = "arkive-relay"
database_id = "d050374e-99db-4d1d-9ff4-ce593233f5c4"

[[r2_buckets]]
binding = "OPS_BUCKET"
bucket_name = "arkive-ops"

[[routes]]
pattern = "relay-arkive.punyakosh.in"
custom_domain = true

[vars]
VAPID_PUBLIC_KEY = "BCBktjdyAXfYbKs28Onbbo6CacxevBMcFxQvGmXkIfEsV3JdIdGxqnYdx_vGGtlb1FvK5J1XfgyUyxLxi6VPPWU"
